### PR TITLE
natives.json builds to b791, better argparser, var filenames

### PR DESCRIPTION
**Pull request by sfinktah**
Okay, so this pull request won't leave with you with an entirely working shiny new application, although it will probably work about as well as it did before, just with a shiny `--help` style interface and some variables that aren't necessarily all used yet.

But by the time you actually accept this merge, it may actually be all shiny and magical.

Seems that my NativeHashFunctionFinder and your NativeGen fit together like a (whatever), I can generate the hash locations out of a live running copy of GTAV quite easily, and create that binary dump file you _badly_ defined.

> _cough_ it is not good practice to define a struct as

`int32 int32 int32
int64 int64
int64 int64
int64 int64
int64 int64
...`

> There is this little thing called struct/byte alignment, where 8 byte vars align across 8 byte memory and disk borders.    Which means it actually stores (in memory, and on disk) as:

`int32 int32 int32 (empty int32)
int64 int64
int64 int64
...`

Anyways, I got it to work, after working out that the offset location you were looking for was `addressInMemory` - `baseAddress` + `IDA loadAddress`.  It's only my TODO list to make the loadAddress run-time configurable BTW.

pps. all my tests were done on b757, so yeah, it does work on versions other than the original. 3 cheers.  although, it's almost pointless since the level of obfu employeed these days is mind-boggling.

image

### CODE REVIEW

**Comment by Fireboyd78** [comment]
Thank you for the pull request. Your feedback is greatly appreciated, but the whole struct thing was a bit uncalled for. I am always open to suggestions and nothing I do is perfect.

I'll go over your pull request more in-depth when I have a chance. Thank you for taking the time to contribute.

**Comment by sfinktah** [comment]
(shrug) I assume you are referring to the command line parser.  No matter, I included the option to output IDAPython scripts directly from my own projects a long time ago, and have deobfu'd all the natives via other python scripts.  Enjoy!

**Comment by Fireboyd78** [comment]
I was actually referring to the "binary dump file you badly defined" part. I know quite a bit about structures in memory -- I got my start with reverse engineering. Alignment is one of the first things I check for. One thing I guess I haven't pointed out clearly enough is that the structs I listed on the readme are _not_ supposed to be interpreted as actual C structs. Yes, this would cause issues with byte-alignment. It's strictly pseudo-code that should be implemented using a binary reader that you retrieve each piece of the data at a time. Read a 4-byte integer, then an 8-byte long, etc.

I've been busy with other projects lately and haven't gotten around to working on this, hence the lack of updates. I apologize if I offended you in any way.

You did introduce some nice changes, I'll give you that. You're right though, I didn't like the command line parser, it was needlessly complicated and probably something I wouldn't include in this sort of project. But there are other areas that definitely show improvement over my original code.

**Comment by sfinktah** [comment]
I can't recall if you pointed out the alignment thing in the docs or not, it was immediately obvious to me anyway... same deal as you with regards to experience.  Just required a `#pragma pack` (or something), I'll confess I had to google it at the time.   I guess you were matching the format to an existing dump, else you would have padded it.

And I didn't write the command line parser, and actually never bothered to implement in my own CLI tool, so I guess I really have nothing to say there :)

But I definately owe you thanks because your tool made me look into IDAPython, which I now love.   I managed to complete de-obfu all the native callback thunks using it, fkn awesome.

Anyways, i'm in the shv skype channel if your still actively in the field.

**Pull request closed without merging**
